# -*- coding: utf-8 -*-
"""polars_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HfBZBy7zhl3lSgNZWQ3b2OL9UB5HmpxO
"""

!pip install kagglehub

import kagglehub

path = kagglehub.dataset_download("amar5693/screen-time-sleep-and-stress-analysis-dataset")

print("Dataset ===> ", path)

import pandas as pd
import numpy as np

dataset = pd.read_csv(f"{path}/Smartphone_Usage_Productivity_Dataset_50000.csv")
dataset.head()

df = dataset

df.head()

df.columns

df.describe()

import polars as pl

pl_df = pl.DataFrame(df)

pl_df.head()

pl_df.describe()

pl_df.shape

len(pl_df.columns)

pl_df.collect_schema()

pl_df.mean()

# [rows, columns]

pl_df[0:25, :]

df[condition]

pl_df.filter(pl.col("Age") > 18)

mean_daily_hours = pl_df.select(pl.col("Daily_Phone_Hours").mean()).item()


pl_df.select(
  pl_df.filter(pl.col("Daily_Phone_Hours") > mean_daily_hours)
  .select("Age").mean()
)



pl_df.group_by("Age").agg(pl.col("Daily_Phone_Hours").sum())



import polars as pl
import kagglehub
import os
import time

def run_enterprise_pipeline():
    # 1. DATA INGESTION
    try:
        path = kagglehub.dataset_download("sobhanmoosavi/us-accidents")
        csv_file = [f for f in os.listdir(path) if f.endswith('.csv')][0]
        data_source = os.path.join(path, csv_file)
    except Exception as e:
        print(f"File Access Error: {e}")
        return

    # 2. DEFINING REUSABLE EXPRESSIONS (Modular Logic)
    duration_mins = (
        (pl.col("End_Time").str.to_datetime(strict=False) -
         pl.col("Start_Time").str.to_datetime(strict=False))
        .dt.total_minutes()
    )

    # Demonstrating: Projection Pushdown, Predicate Pushdown, and Type Casting
    main_plan = (
        pl.scan_csv(data_source, infer_schema_length=10000)
        .select([
            "ID", "Severity", "Start_Time", "End_Time", "State",
            "Temperature(F)", "City", "Visibility(mi)"
        ])
        .filter(
            (pl.col("State").is_in(["CA", "TX", "FL", "NY"])) &
            (pl.col("Severity").is_not_null())
        )
        .with_columns([
            duration_mins.alias("Duration_Mins"),
            pl.col("Temperature(F)").fill_null(strategy="mean")
        ])
        .filter(pl.col("Duration_Mins") > 0)
    )

    analytics_plan = main_plan.with_columns([
        pl.col("Temperature(F)").mean().over("State").alias("State_Avg_Temp"),
        # Rank cities by longest average accident duration
        pl.col("Duration_Mins")
        .rank(method="dense", descending=True)
        .over("State")
        .alias("Severity_Rank_In_State")
    ])

    state_mapping = pl.LazyFrame({
        "State": ["CA", "TX", "FL", "NY"],
        "State_Full_Name": ["California", "Texas", "Florida", "New York"]
    })

    final_plan = analytics_plan.join(state_mapping, on="State", how="left")

    print("LOGICAL AND PHYSICAL QUERY PLAN")
    print("-" * 30)
    print(final_plan.explain())
    print("-" * 30)



    # 7. STREAMING EXECUTION (Out-of-Core Processing)
    # This allows processing datasets larger than physical RAM
    start_time = time.time()

    # execute the plan
    df_result = final_plan.collect(engine="streaming")

    execution_time = time.time() - start_time

    # 8. DATA SINK (Parquet Partitioning)
    # Parquet is the standard for Big Data storage (OLAP)
    output_dir = "optimized_accident_data"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    df_result.write_parquet(
        f"{output_dir}/processed_accidents.parquet",
        compression="zstd"
    )

    print(f"Process Telemetry:")
    print(f"Execution Time: {execution_time:.4f} seconds")
    print(f"Record Count: {df_result.height}")
    print(f"Memory Usage: {df_result.estimated_size('mb'):.2f} MB")
    print(df_result.head(10))

if __name__ == "__main__":
    run_enterprise_pipeline()

final_plan

print("--- Initializing Data Ingestion ---")
dataset_path = kagglehub.dataset_download("sobhanmoosavi/us-accidents")
csv_filename = [f for f in os.listdir(dataset_path) if f.endswith('.csv')][0]
main_file_path = os.path.join(dataset_path, csv_filename)

accidents_lazy = pl.scan_csv(main_file_path, infer_schema_length=10000)

state_metadata_lazy = pl.LazyFrame({
    "State_Abbr": ["CA", "TX", "FL", "NY", "PA", "IL", "OH", "GA", "NC", "MI"],
    "Region": ["West", "South", "South", "Northeast", "Northeast", "Midwest", "Midwest", "South", "South", "Midwest"],
    "Infrastructure_Score": [8.2, 7.1, 6.8, 9.1, 7.5, 7.0, 6.5, 6.9, 7.2, 6.4]
})

accidents_prepared = (
    accidents_lazy
    .select([
        "ID", "Severity", "Start_Time", "State",
        "Temperature(F)", "City", "Visibility(mi)"
    ])
    .rename({"State": "State_Abbr"})
    .filter(pl.col("Temperature(F)").is_not_null())
)

joined_plan = accidents_prepared.join(
    state_metadata_lazy,
    on="State_Abbr",
    how="left"
)

final_plan = joined_plan.with_columns([
    pl.col("Temperature(F)").mean().over("Region").alias("Regional_Avg_Temp"),
    pl.col("Severity").rank(method="dense", descending=True).over("Region").alias("Region_Severity_Rank")
]).filter(pl.col("Region").is_not_null())

print("\n" + "="*50)
print("INTERNAL QUERY PLAN (LOGICAL AND PHYSICAL)")
print("="*50)
print(final_plan.explain())
print("="*50 + "\n")

final_plan.collect()

import polars as pl
import numpy as np
from datetime import datetime, timedelta

# 1. GENERATE DATA (The "Source")
num_rows = 100_000

# Create Sales Fact Table
sales_df = pl.DataFrame({
    "transaction_id": np.arange(num_rows),
    "product_id": np.random.randint(1, 50, num_rows),
    "store_id": np.random.randint(1, 10, num_rows),
    "quantity": np.random.randint(1, 5, num_rows),
    "price": np.random.uniform(10.0, 500.0, num_rows),
    "timestamp": [datetime(2024, 1, 1) + timedelta(minutes=i) for i in range(num_rows)]
}).lazy() # Turn into LazyFrame immediately

# Create Product Dimension Table
product_meta = pl.DataFrame({
    "product_id": np.arange(1, 50),
    "category": np.random.choice(["Electronics", "Appliances", "Furniture", "Toys"], 49),
    "supplier": np.random.choice(["Sup_A", "Sup_B", "Sup_C"], 49)
}).lazy()

print("Synthetic Production Data Generated (100k rows).")

# Nothing happens yet; we are just building the Graph
lazy_plan = sales_df.filter(pl.col("quantity") > 2).select(["transaction_id", "price"])

print("\n--- 1. THE LOGICAL PLAN (DAG) ---")
print(lazy_plan.explain())

# Predicate Pushdown Example
# We join first, THEN filter. Polars will optimize this automatically.
pushdown_query = (
    sales_df
    .join(product_meta, on="product_id")
    .filter(pl.col("category") == "Electronics")
)

print("\n--- 2. OPTIMIZED PUSHDOWN PLAN ---")
# In the output, notice 'FILTER' is placed BEFORE the 'JOIN'
print(pushdown_query.explain())

# Multiple parallel calculations
columnar_plan = sales_df.with_columns([
    (pl.col("price") * pl.col("quantity")).alias("revenue"),
    (pl.col("price") * 0.05).alias("tax"),
    (pl.col("quantity").sum().over("product_id")).alias("total_prod_vol")
])

print("\n--- 3. COLUMNAR EXPRESSIONS (ARROW) ---")
print(columnar_plan.collect().head(5))

columnar_plan.explain()

# Processing in batches
streaming_query = (
    sales_df
    .group_by("store_id")
    .agg(pl.col("price").sum().alias("total_store_revenue"))
)

print("\n--- 4. STREAMING EXECUTION ---")
# collect(streaming=True) is the key Data Engineering command here
result = streaming_query.collect(engine="streaming")
print(result)

# The same expression `pl.col("price").mean()` used in two contexts
query = sales_df.select([
    pl.col('store_id'),
    # Context 1: Global Selection (Mean of the whole table)
    pl.col("price").mean().alias("global_avg"),

    # Context 2: Window Selection (Mean within a specific partition)
    pl.col("price").mean().over("store_id").alias("store_avg")
])

query.collect()

analytics = (
    sales_df
    .group_by("store_id")
    .agg([
        # 1. Simple Aggregation
        pl.col("quantity").sum().alias("total_items"),

        # 2. Filtered Aggregation (Only sum expensive items)
        pl.col("quantity").filter(pl.col("price") > 100).sum().alias("bulk_expensive_items"),

        # 3. Multiple Logical Operations
        (pl.col("price") * pl.col("quantity")).mean().alias("avg_transaction_value")
    ])
)

print(analytics.collect())

# Data Modeling

import polars as pl
import numpy as np

# DIMENSION 1: Products
products_dim = pl.LazyFrame({
    "product_id": [1, 2, 3],
    "category": ["Electronics", "Furniture", "Electronics"],
    "brand": ["Brand_A", "Brand_B", "Brand_A"]
})

# DIMENSION 2: Stores
stores_dim = pl.LazyFrame({
    "store_id": ["S_01", "S_02"],
    "city": ["New York", "London"],
    "region": ["North", "Europe"]
})

# FACT: Sales (1 million records)
sales_fact = pl.DataFrame({
    "order_id": np.arange(1_000_000),
    "product_id": np.random.randint(1, 4, 1_000_000),
    "store_id": np.random.choice(["S_01", "S_02"], 1_000_000),
    "amount": np.random.uniform(10, 1000, 1_000_000)
}).lazy()

# The Model Pipeline
model_query = (
    sales_fact
    # Step 1: Enrich Facts with Dimensions
    .join(products_dim, on="product_id", how="left")
    .join(stores_dim, on="store_id", how="left")

    # Step 2: Filter the Model (Predicate Pushdown)
    .filter(pl.col("category") == "Electronics")

    # Step 3: Complex Analytics (Window Functions)
    .with_columns([
        # Compare each sale to the average of its specific Brand
        pl.col("amount").mean().over("brand").alias("brand_avg_sale"),
        # Total sales per Region
        pl.col("amount").sum().over("region").alias("regional_total")
    ])

    # Step 4: Final Selection (Projection Pushdown)
    .select(["order_id", "city", "brand", "amount", "brand_avg_sale"])
)

model_query.explain()

final_output = model_query.collect(engine="streaming")

final_output

sales_fact = pl.LazyFrame({
    "product_id": [1, 2, 1, 3, 2],
    "quantity": [10, 5, 2, 8, 1],
    "store_id": ["A", "A", "B", "B", "A"]
})

product_dim = pl.LazyFrame({
    "product_id": [1, 2, 3],
    "category": ["Electronics", "Furniture", "Electronics"],
    "unit_price": [100.0, 450.0, 50.0]
})

joined_query = (
    sales_fact
    .join(
        product_dim,
        on="product_id",
        how="left"
    )
    # Perform a columnar calculation across the joined data
    .with_columns([
        (pl.col("quantity") * pl.col("unit_price")).alias("line_total"),

    ])
    # Aggregate to see high-level insights
    .group_by("category")
    .agg(pl.col("line_total").sum())
)

joined_query.collect()

vocab = {"good": 0, "movie": 1, "bad": 2, "film": 3}

for w in "good movie".split():
  print(w)

