# -*- coding: utf-8 -*-
"""pyspark_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mX60QTTMJrECdvswxWwPvJvXgfEDy010
"""

!pip install kagglehub

!python -m pip install --upgrade pip

!pip install findspark

!pip install findspark --trusted-host pypi.org --trusted-host files.pythonhosted.org

!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!wget -q https://downloads.apache.org/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz
!tar xf spark-3.5.0-bin-hadoop3.tgz
!pip install pyspark

!pip install requests

from pyspark.sql import SparkSession
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

spark = SparkSession.builder.appName("PySparkEDA").getOrCreate()

url = "https://api.covid19india.org/data.json"
response = requests.get(url=url)
data = response.json()

len(data["cases_time_series"])

import json

case_time_series = data['cases_time_series']
statewise = data['statewise']
tested = data['tested']

case_time_series_df = spark.createDataFrame(case_time_series)
case_time_series_df.show()
case_time_series_df.printSchema()

statewise_df = spark.createDataFrame(statewise)
statewise_df.show()
statewise_df.printSchema()

tested_df = spark.createDataFrame(tested)
tested_df.show(5)
tested_df.printSchema()

case_time_series_df.count()

case_time_series_df.describe()

